name: paylike_dart_request
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.0
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.3
  mockito: ^5.0.13
  sprintf: ^6.0.0
