name: paylike_dart_request
description: Low level API client for Paylike which helps executing requests in a similiar way as in the JS version
version: 1.0.10
homepage: https://paylike.io
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_runner: ^2.1.0
  mockito: ^5.0.13
  pedantic: ^1.10.0
  shelf: ^1.2.0
  test: ^1.16.0
